import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from df_model_classifier import classify_intake


class ModelClassifierTests(unittest.TestCase):
    def test_explicit_registered_model_is_known(self):
        result = classify_intake({
            "model_id": "cot-cm-external-ramp-tian-2015",
            "target": "Gvc",
            "parameters": {"Vin": 12, "Vo": 1.2, "fs": 300000, "L": 3e-7,
                           "C": 0.00448, "R": 0.1, "rC": 0.00075,
                           "Ri": 0.01, "se_ratio": 1},
        })
        self.assertEqual(result["path"], "KNOWN_MODEL")
        self.assertEqual(result["action"], "use_known_model")
        self.assertEqual(result["topology"], "buck")
        self.assertEqual(result["conduction_mode"], "CCM")
        self.assertEqual(result["phases"], 1)

    def test_modified_registered_model_is_near_not_known(self):
        result = classify_intake({
            "similar_model": "cot-cm-external-ramp-tian-2015",
            "target": "Gvc",
            "topology": "buck",
            "conduction_mode": "CCM",
            "phases": 1,
            "control_family": "external-ramp-cot-current-mode",
            "modifications": ["ramp is generated by an RC network"],
            "switching_events": [{"name": "off_edge", "fixed_or_movable": "movable",
                                  "equation": "F_off=Ri*iL+vramp-vc=0"}],
            "comparator_inputs": {"positive": "vc", "negative": "Ri*iL+vramp"},
            "parameters": {"Vin": 12, "Vo": 1.2, "fs": 300000, "L": 3e-7,
                           "C": 0.00448, "R": 0.1, "rC": 0.00075},
        })
        self.assertEqual(result["path"], "NEAR_MODEL")
        self.assertEqual(result["action"], "derive_by_protocol")

    def test_missing_event_is_incomplete(self):
        result = classify_intake({
            "topology": "buck", "conduction_mode": "CCM", "phases": 1,
            "control_family": "custom-cot", "target": "Gvc",
            "parameters": {"Vin": 12, "L": 3e-7, "C": 470e-6},
        })
        self.assertEqual(result["path"], "INCOMPLETE")
        self.assertIn("switching_events", result["missing_information"])
        self.assertEqual(result["action"], "ask_for_missing_info")

    def test_multiphase_overlap_is_unsupported(self):
        result = classify_intake({
            "topology": "buck", "conduction_mode": "CCM", "phases": 4,
            "multiphase_overlap": True, "target": "Gvc",
        })
        self.assertEqual(result["path"], "UNSUPPORTED")
        self.assertEqual(result["validation_level"], "REJECTED_UNSUPPORTED")

    def test_average_model_cannot_be_declared_df(self):
        result = classify_intake({
            "topology": "buck", "conduction_mode": "CCM", "phases": 1,
            "average_model_as_df": True, "target": "Gvc",
        })
        self.assertEqual(result["path"], "UNSUPPORTED")
        self.assertIn("average-model-as-df", result["unsupported_effects"])


if __name__ == "__main__":
    unittest.main()
